Feature/fake ss node
Ehco1996/django-sspanel pull request #442
Opened 2020-11-13 10:05 UTC by Okeyja

给客户端的假SS节点，name："剩余{}GB，等级{}，等级剩余{}天"

请先处理 poetry PR

2020-11-13 10:28 UTC, Ehco1996 requested changes
感谢pr，留了几个小comment

另外如果有兴趣可以接着这个fake node去把
https://github.com/Ehco1996/django-sspanel/issues/431
这个issue实现一下？，当然如果不想实现也没事哈

2020-11-13 10:28 UTC, Ehco1996 commented on apps/sspanel/models.py
> +        now = datetime.datetime.now().replace(tzinfo=pytz.timezone("UTC"))
这里可以用`apps.utils.get_current_datetime`这个函数来实现这个功能哦

2020-11-13 10:28 UTC, Ehco1996 commented on apps/sspanel/models.py
> +        ONE_GIGA_BYTES = 1073741824
`ONE_GIGA_BYTES`可以从setting里取`GB`这个变量

2020-11-13 22:39 UTC, Okeyja commented
您是说把官网地址加上吗？好的。等我把poetry的集成做了吧。

2020-11-14 08:21 UTC, closed without merging

2020-11-15 13:52 UTC, Gkirito commented
来大佬们下面吃瓜，我都用PyCharm默认的Virtualeny Environment，hhh，我用用poetry试试